# Generated by Django 6.1 on 2026-08-28 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='organization.establishment', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='role',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='organization.establishment', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establishment', to='organization.establishment', verbose_name='Establecimiento'),
        ),
    ]
