# Generated by Django 6.1 on 2026-08-28 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_departmentleadership_options'),
        ('users', '0002_alter_avatar_establishment_alter_role_establishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_employee', to='organization.employee', verbose_name='Funcionario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_establishment', to='organization.establishment', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='users.role', verbose_name='Rol'),
        ),
    ]
