# Generated by Django 6.1 on 2026-08-27 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre legal')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tax_id', models.CharField(max_length=30, verbose_name='RUC/CIF')),
                ('state_province', models.CharField(max_length=60, verbose_name='Estado/Provincia')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=150, verbose_name='Dirección')),
                ('zip_code', models.IntegerField(verbose_name='Código postal')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=150, verbose_name='Correo electrónico')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Nombre de contacto')),
                ('contact_role', models.CharField(max_length=150, verbose_name='Rol de contacto')),
                ('category', models.CharField(max_length=150, verbose_name='Categoría')),
                ('payment_terms', models.CharField(max_length=150, verbose_name='Condiciones de pago')),
                ('payment_method', models.CharField(max_length=150, verbose_name='Método de pago')),
                ('bank_account', models.CharField(max_length=150, verbose_name='Cuenta bancaria')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_country', to='core.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
    ]
