# Generated by Django 6.1 on 2026-08-23 11:59

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.CreateModel(
            name='HistoricalSupplier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre legal')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tax_id', models.CharField(max_length=30, verbose_name='RUC/CIF')),
                ('country', models.CharField(max_length=60, verbose_name='País')),
                ('state_province', models.CharField(max_length=60, verbose_name='Estado/Provincia')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=150, verbose_name='Dirección')),
                ('zip_code', models.IntegerField(verbose_name='Código postal')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=150, verbose_name='Correo electrónico')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Nombre de contacto')),
                ('contact_role', models.CharField(max_length=150, verbose_name='Rol de contacto')),
                ('category', models.CharField(max_length=150, verbose_name='Categoría')),
                ('payment_terms', models.CharField(max_length=150, verbose_name='Condiciones de pago')),
                ('currency', models.CharField(max_length=150, verbose_name='Moneda')),
                ('payment_method', models.CharField(max_length=150, verbose_name='Método de pago')),
                ('bank_account', models.CharField(max_length=150, verbose_name='Cuenta bancaria')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'historical Proveedor',
                'verbose_name_plural': 'historical Proveedores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
