# Generated by Django 6.1 on 2026-08-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
    ]
