# Generated by Django 6.1 on 2026-08-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentleadership',
            options={'ordering': ['employee'], 'verbose_name': 'Jefatura', 'verbose_name_plural': 'Jefaturas'},
        ),
    ]
