# Generated by Django 6.1 on 2026-08-23 14:31

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('run', models.CharField(max_length=20, unique=True, verbose_name='RUN')),
                ('alias', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Alias')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('anexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Anexo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='establecimientos/logos/&Y', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEstablishment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('run', models.CharField(db_index=True, max_length=20, verbose_name='RUN')),
                ('alias', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Alias')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('anexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Anexo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('logo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Establecimiento',
                'verbose_name_plural': 'historical Establecimientos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
