# Generated by Django 6.1 on 2026-08-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('run', models.CharField(max_length=20, unique=True, verbose_name='RUN')),
                ('alias', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Alias')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('anexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Anexo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='establecimientos/logos/&Y', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
            },
        ),
    ]
