# Generated by Django 6.1 on 2026-08-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('customers', '0003_alter_customer_establishment'),
        ('inventory', '0003_alter_inventorymovements_establishment_and_more'),
        ('purchases', '0003_alter_goodsreceipstatus_establishment_and_more'),
        ('users', '0002_alter_avatar_establishment_alter_role_establishment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Establishment',
        ),
    ]
