# Generated by Django 6.1 on 2026-08-24 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_initial'),
        ('suppliers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=50, verbose_name='Simbolo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'Estado de Orden',
                'verbose_name_plural': 'Estados de Ordenes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchasesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('estimated_deñivery_date', models.DateField(verbose_name='Fecha Estimada de Entrega')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order', to='suppliers.supplier', verbose_name='Proveedor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Ordenes de compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LinesPurchasesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('received_quantity', models.PositiveIntegerField(verbose_name='Cantidad Recibida')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_purchases_currency', to='suppliers.currency', verbose_name='Moneda')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_purchases_order_material', to='materials.material', verbose_name='Material')),
                ('unit_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_purchases_unit_material', to='materials.unit', verbose_name='Unidad de Material')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_purchases_order', to='purchases.purchasesorder', verbose_name='Orden de compra')),
            ],
            options={
                'verbose_name': 'Liena de orden de compra',
                'verbose_name_plural': 'Líneas de ordenes de compra',
                'ordering': ['id'],
            },
        ),
    ]
