# Generated by Django 6.1 on 2026-08-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=50, verbose_name='Simbolo')),
            ],
            options={
                'verbose_name': 'Estado de recepción de Mercancía',
                'verbose_name_plural': 'Estados de recepción de Mercancías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LinesPurchasesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posición')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida')),
            ],
            options={
                'verbose_name': 'Liena de orden de compra',
                'verbose_name_plural': 'Líneas de ordenes de compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=50, verbose_name='Simbolo')),
            ],
            options={
                'verbose_name': 'Estado de Orden',
                'verbose_name_plural': 'Estados de Ordenes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchasesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='¿Esta Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Código')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('estimated_delivery_date', models.DateField(verbose_name='Fecha Estimada de Entrega')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Ordenes de compra',
                'ordering': ['id'],
            },
        ),
    ]
