# Generated by Django 6.1 on 2026-08-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasesorder',
            old_name='estimated_deñivery_date',
            new_name='estimated_delivery_date',
        ),
    ]
