# Generated by Django 6.0 on 2026-08-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_rename_estimated_deñivery_date_purchasesorder_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linespurchasesorder',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida'),
        ),
    ]
