# Generated by Django 6.1 on 2026-08-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorymovements_establishment_and_more'),
        ('organization', '0002_alter_departmentleadership_options'),
        ('purchases', '0003_alter_goodsreceipstatus_establishment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesorder',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_department_order', to='organization.department', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='purchasesorder',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_inventory_order', to='inventory.locationinventory', verbose_name='Bodega'),
        ),
    ]
