# Generated by Django 6.1 on 2026-08-26 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('suppliers', '0003_alter_currency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovements',
            options={'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AddField(
            model_name='inventorymovements',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_currency', to='suppliers.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='inventorymovements',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
