# Generated by Django 6.1 on 2026-08-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
