# Generated by Django 6.1 on 2026-08-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Tipo de Producto', 'verbose_name_plural': 'Tipos de Productos'},
        ),
    ]
